//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace admin.net.azurewebsites.anperowsv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="storeSrvSoap", Namespace="http://tempuri.org/")]
    public partial class storeSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateSeriaCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeriaListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSeriaCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public storeSrv() {
            this.Url = global::admin.Properties.Settings.Default.admin_net_azurewebsites_anperowsv_storeSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateSeriaCodeCompletedEventHandler UpdateSeriaCodeCompleted;
        
        /// <remarks/>
        public event GetSeriaListCompletedEventHandler GetSeriaListCompleted;
        
        /// <remarks/>
        public event AddSeriaCodeCompletedEventHandler AddSeriaCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSeriaCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateSeriaCode(string ListCode, string status, string tokenkey, string synTime, int storeId, int UID) {
            object[] results = this.Invoke("UpdateSeriaCode", new object[] {
                        ListCode,
                        status,
                        tokenkey,
                        synTime,
                        storeId,
                        UID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSeriaCodeAsync(string ListCode, string status, string tokenkey, string synTime, int storeId, int UID) {
            this.UpdateSeriaCodeAsync(ListCode, status, tokenkey, synTime, storeId, UID, null);
        }
        
        /// <remarks/>
        public void UpdateSeriaCodeAsync(string ListCode, string status, string tokenkey, string synTime, int storeId, int UID, object userState) {
            if ((this.UpdateSeriaCodeOperationCompleted == null)) {
                this.UpdateSeriaCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSeriaCodeOperationCompleted);
            }
            this.InvokeAsync("UpdateSeriaCode", new object[] {
                        ListCode,
                        status,
                        tokenkey,
                        synTime,
                        storeId,
                        UID}, this.UpdateSeriaCodeOperationCompleted, userState);
        }
        
        private void OnUpdateSeriaCodeOperationCompleted(object arg) {
            if ((this.UpdateSeriaCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSeriaCodeCompleted(this, new UpdateSeriaCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSeriaList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSeriaList(string monthAdd, string usedStatus, string lockedByuser, string addToStore, int beginRow, int endRow, string tokenkey, string synTime) {
            object[] results = this.Invoke("GetSeriaList", new object[] {
                        monthAdd,
                        usedStatus,
                        lockedByuser,
                        addToStore,
                        beginRow,
                        endRow,
                        tokenkey,
                        synTime});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSeriaListAsync(string monthAdd, string usedStatus, string lockedByuser, string addToStore, int beginRow, int endRow, string tokenkey, string synTime) {
            this.GetSeriaListAsync(monthAdd, usedStatus, lockedByuser, addToStore, beginRow, endRow, tokenkey, synTime, null);
        }
        
        /// <remarks/>
        public void GetSeriaListAsync(string monthAdd, string usedStatus, string lockedByuser, string addToStore, int beginRow, int endRow, string tokenkey, string synTime, object userState) {
            if ((this.GetSeriaListOperationCompleted == null)) {
                this.GetSeriaListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeriaListOperationCompleted);
            }
            this.InvokeAsync("GetSeriaList", new object[] {
                        monthAdd,
                        usedStatus,
                        lockedByuser,
                        addToStore,
                        beginRow,
                        endRow,
                        tokenkey,
                        synTime}, this.GetSeriaListOperationCompleted, userState);
        }
        
        private void OnGetSeriaListOperationCompleted(object arg) {
            if ((this.GetSeriaListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeriaListCompleted(this, new GetSeriaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSeriaCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddSeriaCode(int montToAdd, int quantity, string tokenkey, string synchTimeNow) {
            object[] results = this.Invoke("AddSeriaCode", new object[] {
                        montToAdd,
                        quantity,
                        tokenkey,
                        synchTimeNow});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddSeriaCodeAsync(int montToAdd, int quantity, string tokenkey, string synchTimeNow) {
            this.AddSeriaCodeAsync(montToAdd, quantity, tokenkey, synchTimeNow, null);
        }
        
        /// <remarks/>
        public void AddSeriaCodeAsync(int montToAdd, int quantity, string tokenkey, string synchTimeNow, object userState) {
            if ((this.AddSeriaCodeOperationCompleted == null)) {
                this.AddSeriaCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSeriaCodeOperationCompleted);
            }
            this.InvokeAsync("AddSeriaCode", new object[] {
                        montToAdd,
                        quantity,
                        tokenkey,
                        synchTimeNow}, this.AddSeriaCodeOperationCompleted, userState);
        }
        
        private void OnAddSeriaCodeOperationCompleted(object arg) {
            if ((this.AddSeriaCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSeriaCodeCompleted(this, new AddSeriaCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateSeriaCodeCompletedEventHandler(object sender, UpdateSeriaCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSeriaCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSeriaCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSeriaListCompletedEventHandler(object sender, GetSeriaListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeriaListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeriaListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AddSeriaCodeCompletedEventHandler(object sender, AddSeriaCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSeriaCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSeriaCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591